config/routes.rb
Rails.application.routes.draw do
  devise_for :freelancers
  devise_for :employers
  root to: 'home#index' 
  get 'freelancer_proposals', to: 'freelancers#freelancer_proposals'
 

  resources :lancer_infos, only: [:index, :show, :new, :create, :edit, :update]  
  resources :projects, only: [ :index, :show, :new, :create, :update] do
    get 'employer_profile', on: :collection 
    get 'avaiable', on: :collection
    get 'freelancer_team', on: :collection
    post 'running', on: :collection
    post 'closed', on: :collection

    resources :proposals, only: [ :index, :show, :create] do     
      post 'accept', on: :member
      get 'reject_justify', on: :member
      post 'reject', on: :member
      post 'cancel', on: :member
      end   
  end
  resources :proposals, only: [:show, :destroy, :edit, :update]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index        
    end    
end

app/views/home/index.html.erb
<h1>Easylancer<h1>
<h3><i> Bem vindo a sua plataforma de freelance!</i> <h3>

<% if not (freelancer_signed_in? or employer_signed_in?) %> 
    <% 'Crie sua conta!' %> 
    <%= link_to 'REGISTRE-SE AQUI COMO FREELANCER',  new_freelancer_registration_url %></a>
    <br>
    <%= link_to 'REGISTRE-SE AQUI COMO CONTRATADOR',  new_employer_registration_url %></a>
<% end %>



<% if freelancer_signed_in? %>           
   
    <% if (LancerInfo.find_by(freelancer:current_freelancer)==nil) %> 
        <%= link_to 'Crie seu perfil para acessar ',  new_lancer_info_path %></a>
        <br> 
    <% elsif (LancerInfo.find_by(freelancer:current_freelancer).errors.empty?)%>     
        <a class="nav-link"><%= link_to 'Meu perfil', lancer_infos_path %></a>
        
        <br>  
         <a class="nav-link"><%= link_to 'Editar perfil', edit_lancer_info_path(current_freelancer.id) %></a>
        <br>         
        <a class="nav-link"><%= link_to 'Projetos disponíveis', avaiable_projects_path %></a>  
        <br>         
        <a class="nav-link"><%= link_to 'Meus Projetos', freelancer_proposals_path %></a>      
        
    <% end %>
    
<% end %>

<br> <br> 
<% if employer_signed_in? %> 
     <%= link_to 'Meus projetos ',  employer_profile_projects_path %></a>
     <br> 
     <%= link_to 'Criar um projeto',  new_project_path %></a>
<% end %>