config/routes.rb
Rails.application.routes.draw do
  devise_for :freelancers
  devise_for :employers
  root to: 'home#index' 
  get 'freelancer_proposals', to: 'freelancers#freelancer_proposals'
 

  resources :lancer_infos, only: [:index, :show, :new, :create, :edit, :update]  
  resources :projects, only: [ :index, :show, :new, :create, :update] do
    get 'employer_profile', on: :collection 
    get 'avaiable', on: :collection
    get 'freelancer_team', on: :collection
    post 'running', on: :collection
    post 'closed', on: :collection

    resources :proposals, only: [ :index, :show, :create] do     
      post 'accept', on: :member
      get 'reject_justify', on: :member
      post 'reject', on: :member
      post 'cancel', on: :member
      end   
  end
  resources :proposals, only: [:show, :destroy, :edit, :update]

end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :employer
    belongs_to :area
    has_many :proposals, dependent: :nullify

    
    enum status: {open: 5, full: 10, running: 20, closed: 30}

    validates :title,  
    :description, 
    :value_hour,
    :limit_proposal,
    :start_date,
    :end_date,
    :squad_num,
    :adress,
    :city ,            
    :area_id,
    presence: true


    validate :minimum_team
    validate :project_init_past
    validate :project_end_past
    validate :end_date_after_start_date
    validate :proposal_past

  
    private
    def minimum_team
        return if squad_num.blank? 
        if squad_num < 1
            errors.add(:squad_num , 'Projeto deve conter pelo menos 1 colaborador') 
        end
    end

    def project_init_past
        return if start_date.blank? 
        
        if start_date< Date.today
            errors.add(:start_date, 'não pode ser em datas passadas') 
        end  
   end

   def proposal_past
        return if limit_proposal.blank? 
        if limit_proposal < Date.today
            errors.add(:limit_proposal, 'não pode ser em datas passadas') 
        end
    end


    def project_end_past
        return if start_date.blank? 
        if end_date < Date.today
            errors.add(:end_date, 'não pode ser em datas passadas') 
        end
    end

    def end_date_after_start_date
        return if end_date.blank? || start_date.blank?
    
        if end_date < start_date
          errors.add(:end_date, "deve ser depois da data de início do projeto")
        end
    end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController    
    before_action :authenticate_employer!, only: [:new, :create, :employer_profile,
        :running, :closed]
    before_action :authenticate_freelancer!, only: [:avaiable, :freelancer_team ]
    
    
    def show        
        @project = Project.find(params[:id])
        @proposal= Proposal.new
        
    end   

    def new
        @project = Project.new  
 
    end

    def create
        
        @project = Project.new(data_params)

        @project.employer = current_employer   
        
        if @project.save       
            render :show           
        else
            render :new
        end

    end

    def avaiable  
        @projects= Project.open           
    end

    def employer_profile                    
        @open_projects = Project.where(employer_id:current_employer.id, status:'open') 
        @full_projects = Project.where(employer_id:current_employer.id, status:'full') 
        @running_projects = Project.where(employer_id:current_employer.id, status:'running') 
        @projects= @open_projects +  @full_projects + @running_projects 
         

    end

    def running
        @project = Project.find(params[:format])
        @project.running!
        @project.save
        redirect_to @project, notice: t('.success')  

    end

    def closed
        @project = Project.find(params[:format])
        @project.closed!
        @project.save   
        redirect_to employer_profile_projects_path, notice: t('.success')     
    end



    def freelancer_team     
        @proposal = Proposal.find(params[:format])
        @project_id =  @proposal.project_id
        @proposals = Proposal.where(project_id:@project_id, status:'accepted')
    end


    private            

    def data_params
        params.require(:project).permit(
            :title,  
            :description, 
            :value_hour,
            :limit_proposal,
            :start_date,
            :end_date,
            :squad_num,
            :adress ,
            :city ,            
            :area_id,
            :remote
        )
        
    end

end

app/views/projects/avaiable.html.erb
<h3> Projetos disponíveis: <h3>

<%if @projects.empty? %> 
   <h4> Nenhum projeto disponível </h4>
<%else%>       
   <%@projects.each do |p|%>
    <%= link_to p.title, project_path(p.id)%>
    <br>
   <%end%> 

<%end%>  

 <br>
 <br>

<%= link_to "Voltar", root_path%>

app/views/projects/employer_profile.html.erb
<h3> Meus Projetos: <h3>
<%=current_freelancer.blank?%>

<%if @projects.empty? %> 
   <h4> Você ainda possui projetos</h4>
<%end%>

<%if @open_projects.any? %>    
 <h4> Projetos em aberto </h4> 
   <%@open_projects.each do |p|%>
   <%= link_to p.title, project_path(p.id)%>
   <br>
   <%end%>
<%end%>  

<%if @full_projects.any? %>    
 <h4> Projetos com colaboradores completos </h4> 
   <%@full_projects.each do |p|%>
   <%= link_to p.title, project_path(p.id)%>
   <br>
   <%end%>
<%end%>  

<%if @running_projects.any? %>    
 <h4> Projetos em andamento </h4> 
   <%@running_projects.each do |p|%>
   <%= link_to p.title, project_path(p.id)%>
   <br>
   <%end%>
<%end%>  





       

app/views/projects/freelancer_team.html.erb
 
<h3>Veja os componetes de sua equipe: </h3>


 <% @proposals.each do |prop| %> 
        <% freelancer= Freelancer.find(prop.freelancer_id) %> 
        <% lancer_info = LancerInfo.find(freelancer.id)%> 
        <%= link_to "#{lancer_info.name}- - -#{freelancer.email}" , lancer_info %>   
          
          
       <br> 
       <br>   

<%end %>

app/views/projects/new.html.erb
<% if @project.errors.any? %>
  <ul>
  <% @project.errors.full_messages.each do |e|%>
   <li><%= e %>
   <%end%>
  </ul>
<%end%>


<%=form_with model: @project do |f| %>
    <div>   
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>
    
    <div> 
    <%= f.label :description %>
    <%= f.text_field :description %>
    </div>
    
    <div> 
    <%= f.label :value_hour %>
    <%= f.number_field :value_hour, min: 0 %>
    </div>

    <div> 
    <%= f.label  :limit_proposal  %>
    <%= f.date_field  :limit_proposal  %>
    </div>

    <div> 
    <%= f.label  :start_date  %>
    <%= f.date_field  :start_date  %>
    </div>

    <div> 
    <%= f.label  :end_date  %>
    <%= f.date_field  :end_date  %>
    </div>
   
    <div> 
    <%= f.label :squad_num %>
    <%= f.number_field :squad_num, step: 1, min: 1 %>
    </div>

    <div>
    <%= f.check_box :remote %>
    <%= f.label :remote, 'Remoto?' %>
    </div>

    <div> 
    <%= f.label :adress %>
    <%= f.text_field :adress %>
    </div>

    <div> 
    <%= f.label :city %>
    <%= f.text_field :city %>
    </div>

    <div> 
    <%= f.label :area_id, "Especialidade desejada" %> 
    <%= f.collection_select :area_id, Area.all, :id, :name, prompt: 'Escolha um tipo' %>
    </div>    

   <%= f.submit 'Enviar' %>
<% end %>

app/views/projects/show.html.erb
<h3> Dados do projeto </h3>


Título: <%= @project.title%>
<br>
Descrição: <%= @project.description %>
<br>
Remuneração máxima por hora: <%= number_to_currency(@project.value_hour)%>
<br>
Colaboradore(s) requerido(s): <%= @project.squad_num%>
<br>
Data limite para candidaturas: <%= l @project.limit_proposal%>
<br>
Previsão de início: <%= l @project.start_date%>
<br>
Previsão de fim: <%= l @project.end_date%>
<br>
Especialidade desejada: <%= Area.find(@project.area_id).name %>
<br>
Remoto: <%= @project.remote ?  'Sim' : 'Não' %>
<br>
Endereço: <%= @project.adress%>
 - <%= @project.city %>
 <br>
 <br>
 <h3> Situação do projeto: <%= Project.human_enum_name(:status, @project.status)%> </h3>

<% if employer_signed_in? && @project.employer==current_employer%>

    <% if @project.status == 'open' ||  @project.status == 'full'%>
        <%= link_to 'Iniciar projeto', running_projects_path(@project.id), method: :post, 
        data: {confirm: "Tem certeza que quer iniciar o projeto?"} %>
    <% elsif @project.status == 'running'%>
        <%= link_to 'Encerrar projeto', closed_projects_path(@project.id), method: :post, 
        data: {confirm: "Tem certeza que quer encerrar o projeto?"} %>
    <% end %>
    
     <br>
     <br>
    <% if @project.proposals.any?%>
     <h3>  Propostas para o projeto: </h3>
     <%else%>
        <h3> Você ainda não possui propostas para esse projeto </h3>
    <%end%>


    <% @project.proposals.each do |proposal| %>
        <% if (proposal.status=='accepted') %>
           <h4> Proposta aceita:</h4>
            Proposta de <%= link_to proposal.freelancer.email,lancer_info_path(proposal.freelancer_id)  %>  <br>         
            Mensagem: <%= proposal.message %>            <br>
            Previsão de término: <%= l proposal.expected_end %>            <br>
            Horas disponíveis por semana: <%= proposal.week_availability %>            <br>
            Valor pedido por hora: <%= number_to_currency proposal.claim_hour %>            <br><br>
        
        <% elsif (proposal.status=='pending') %>
            <h4> Proposta pendente:</h4>
            Proposta de <%= link_to proposal.freelancer.email,lancer_info_path(proposal.freelancer_id)  %>  <br>         
            Mensagem: <%= proposal.message %>            <br>
            Previsão de término: <%= l proposal.expected_end %>            <br>
            Horas disponíveis por semana: <%= proposal.week_availability %>            <br>
            Valor pedido por hora: <%= number_to_currency proposal.claim_hour %>            <br>
             <%= link_to 'Aceitar proposta de '+ proposal.freelancer.email,  
             accept_project_proposal_path(proposal.id), method: :post %>
             <br>             
             <%= link_to 'Recusar proposta de '+ proposal.freelancer.email,  
             reject_justify_project_proposal_path(proposal.id) %> <br> 
      
            <br><br>
        <% end %>

     <% end %> 
            
             
    
<% elsif freelancer_signed_in?%>
    

    <% emails=[]%>     
    <% @project.proposals.each do |p| %> 
        <% emails<<p.freelancer.email %>    
        <% end %> 
    


    <% if (emails.include?(current_freelancer.email))%> 
        <br>
        <br>
        Você já enviou uma proposta para esse projeto!       
        
           
     <% elsif (@project.status=='open')%> 
        


        Faça uma proposta para esse projeto!:
        <%=form_with model: @proposal,url: project_proposals_path(@project.id) do |f| %> 
        <%= f.label :message, 'Mensagem' %>
        <%= f.text_field :message %> 
        <br>
        <%= f.label :week_availability, 'Horas disponíveis por semana' %>
        <%= f.number_field :week_availability %> 
        <br>
        <%= f.label :expected_end, 'Entrega prevista' %>
        <%= f.date_field :expected_end %> 
        <br>
        <%= f.label :claim_hour, 'Pretensão salarial por hora - R$' %>
        <%= f.number_field :claim_hour %>        
        <br>    
        <%= f.submit 'Enviar proposta' %>  
        <% end %> 
    <% elsif %>
        <br>
        <br>
        Esse projeto não esta mais disponível!   

    <% end %>

<% end %>


<br>
<br>
<%= link_to "Voltar", root_path%>