config/routes.rb
Rails.application.routes.draw do
  devise_for :freelancers
  devise_for :employers
  root to: 'home#index' 
  get 'freelancer_proposals', to: 'freelancers#freelancer_proposals'
 

  resources :lancer_infos, only: [:index, :show, :new, :create, :edit, :update]  
  resources :projects, only: [ :index, :show, :new, :create, :update] do
    get 'employer_profile', on: :collection 
    get 'avaiable', on: :collection
    get 'freelancer_team', on: :collection
    post 'running', on: :collection
    post 'closed', on: :collection

    resources :proposals, only: [ :index, :show, :create] do     
      post 'accept', on: :member
      get 'reject_justify', on: :member
      post 'reject', on: :member
      post 'cancel', on: :member
      end   
  end
  resources :proposals, only: [:show, :destroy, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easylancer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-lg " style="background-color: #CE93D8; >

  <% if employer_signed_in? %>    
    <span class="navbar-text mx-3"> Você esta logado como o contratador:  
    <a class="nav-link active"> <%= current_employer.email %></a></span> 
    <button type="button" class="btn btn-warning mx-3">
        <%= link_to 'Logout', destroy_employer_session_path, method: :delete %>       
    </button>
  <% elsif freelancer_signed_in? %>  
    <span class="navbar-text mx-3"> Você esta logado como o freelancer </span>  
    <a class="nav-link active"> <%= current_freelancer.email %></a>
     <button type="button" class="btn btn-warning mx-3">
        <%= link_to 'Logout', destroy_freelancer_session_path, method: :delete %>   
      </button>
          
        
  <% else %>     
          <span class="navbar-text mx-3"> Faça seu login para buscar ou oferecer um freelance!</span>  
          <ul>
            <li>
            <a class="nav-link mx-3"><%= link_to 'Entrar como contratador', new_employer_session_path %></a>
            </li>
            <li>
            <%= link_to 'Cadastre-se como contratador',  new_employer_registration_url %></a>
            </li>
          </ul>

          <ul>
            <li>
            <a class="nav-link mx-3"><%= link_to 'Entrar como freelancer', new_freelancer_session_path %></a>
            </li>
            <li>
            <%= link_to 'Cadastre-se como freelancer',  new_freelancer_registration_url %></a>
            </li>
           </ul>
      <% end %>   
      <br>   
      <% if not current_page?(root_path)%>
        <a class="nav-link active mx-3"><%= link_to "Voltar para pagina principal", root_path%>
      <% end %>
  </nav>

  <body>
    <p><%= notice %></p>
    <p><%= alert %></p>
    <%= yield %>
  </body>
</html>